#!/bin/sh
node_modules/istanbul/lib/cli.js cover node_modules/mocha/bin/_mocha
resources/pmd-bin-5.4.0/bin/run.sh pmd -d lib/randomstring.js -f xml -R ruleset.xml -language javascript > pmd.xml
./check_keys.sh
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
  echo ""
  echo "Private keys enclosed!"
  echo "ABORTING commmit!"
  exit 1
fi
node parser.js
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
  echo ""
  echo "Coverage or custom static analysis rule failed!"
  echo "ABORTING commmit!"
  exit 1
fi
